'use client';

/**
 * Onboarding: everything between "signed in with Google" and "has wallets".
 *
 * A signed-in user with an empty address previously landed on the Create screen and pressed the button,
 * which failed on gas or on IKA — an error is a poor way to learn that a wallet needs funding. This makes
 * the sequence explicit (fund, then create, then done), states the two fees in terms of what they buy, and
 * refuses to offer the action until it can succeed.
 *
 * Presentational by design: it owns no balances, no polling and no transaction. Every value and every
 * decision arrives as a prop, so the same component renders identically in a test, a story, or the app —
 * and the creation pipeline stays where it can be reasoned about.
 */

import { useId, type ReactElement } from 'react';
import { AnimatePresence, motion, useReducedMotion, type MotionProps } from 'framer-motion';
import { AlertTriangle, ArrowRight, Check } from 'lucide-react';
import { Button, ErrorNote, StatusNote } from '@/components/ui';
import { FlowStepper } from './FlowStepper';
import { FundPanel } from './FundPanel';
import { CreationChecklist } from './CreationChecklist';
import type { OnboardStage, OnboardingProps } from './types';

// The types live in `./types` so the stepper can name a stage without importing its own parent, but this
// module stays the one place a caller has to know about.
export type { OnboardStage, OnboardingProps };

/**
 * The page title changes with the stage, and it is the fastest thing a returning user reads.
 *
 * Kept as data rather than inline JSX so the four stages can be compared side by side — that is the only
 * way to keep the tone consistent and each promise ("about a minute", "once") stated in exactly one place.
 */
const HEADINGS: Record<OnboardStage, { eyebrow: string; title: string; body: string }> = {
  fund: {
    eyebrow: 'One-time setup',
    title: 'Fund your account',
    body: 'Your keys are generated by the Ika validator network and recorded on Sui, and both of those charge a fee. Add SUI and IKA to the address below to continue.',
  },
  create: {
    eyebrow: 'One-time setup',
    title: 'Create your wallets',
    body: 'One pass generates the keys behind every chain. Each key is split across the Ika network, so no single party — including us — ever holds a whole one.',
  },
  working: {
    eyebrow: 'Working · keep this tab open',
    title: 'Creating your wallets',
    body: 'This takes about a minute, most of it spent waiting on the validator network to produce your key shares.',
  },
  done: {
    eyebrow: 'Setup complete',
    title: 'Your wallets are ready',
    body: 'Every chain is now live under your Google account. This was the one-time part — from here you just send and receive.',
  },
};

export function Onboarding({
  address,
  suiBalance,
  ikaBalance,
  funded,
  stage,
  activeStepIndex,
  statusMessage,
  steps,
  error,
  acquireIkaUrl,
  onCreate,
  onRefreshBalances,
  onFinish,
  refreshing,
}: OnboardingProps): ReactElement {
  const hintId = useId();

  /**
   * framer-motion animates via inline transforms, which the global `prefers-reduced-motion` CSS override
   * cannot reach — so the preference has to be honoured here in JS or it is not honoured at all.
   */
  const reduceMotion = useReducedMotion();
  const stageMotion: MotionProps = reduceMotion
    ? {}
    : {
        initial: { opacity: 0, y: 8 },
        animate: { opacity: 1, y: 0 },
        exit: { opacity: 0, y: -8 },
        transition: { duration: 0.18 },
      };

  const heading = HEADINGS[stage];
  const funding = stage === 'fund' || stage === 'create';

  return (
    <div className="w-full max-w-xl mx-auto space-y-6">
      <FlowStepper stage={stage} />

      <header className="text-center space-y-2.5">
        <div className="mono-label">{heading.eyebrow}</div>
        <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight leading-tight text-balance">
          {heading.title}
        </h1>
        <p className="text-sm text-[var(--muted)] leading-relaxed max-w-md mx-auto">{heading.body}</p>
      </header>

      {/* `mode="wait"` so the outgoing stage clears before the next arrives; two cards crossfading on top
          of each other in a flow this consequential looks like a glitch, not a transition. */}
      <AnimatePresence mode="wait">
        <motion.div key={stage} {...stageMotion} className="space-y-4">
          {funding && (
            <>
              <FundPanel
                address={address}
                suiBalance={suiBalance}
                ikaBalance={ikaBalance}
                funded={funded}
                acquireIkaUrl={acquireIkaUrl}
                onRefreshBalances={onRefreshBalances}
                refreshing={refreshing}
              />

              {error && <ErrorNote {...error} />}

              <div className="space-y-2">
                <Button
                  size="lg"
                  onClick={onCreate}
                  disabled={!funded}
                  // A disabled button states no reason on its own; the hint below is that reason, so it is
                  // wired to the control rather than left as nearby text a screen reader may never reach.
                  aria-describedby={hintId}
                  className="w-full"
                >
                  Create my wallets
                  <ArrowRight className="w-4 h-4 shrink-0" aria-hidden />
                </Button>
                <p
                  id={hintId}
                  className="text-[11px] text-[var(--muted-2)] text-center leading-relaxed"
                >
                  {funded
                    ? 'Takes about a minute. Nothing else to approve — zkLogin signs for you.'
                    : 'Enabled as soon as both balances arrive.'}
                </p>
              </div>
            </>
          )}

          {stage === 'working' && (
            <>
              <div className="card p-4 sm:p-5 space-y-4">
                <CreationChecklist steps={steps} activeStepIndex={activeStepIndex} />
                {/* StatusNote carries the aria-live region, so the pipeline's own words are announced as
                    they change. The fallback avoids an empty live region between steps. */}
                <StatusNote>{statusMessage || 'Working…'}</StatusNote>
              </div>

              {/* Amber, not red: nothing is wrong, but leaving now costs the fees already spent and leaves
                  a half-created wallet the user would have to reconcile. Every control that could take
                  them off this screen — refresh, the swap link, the primary action — is unmounted above. */}
              <div className="rounded-[var(--radius-sm)] border border-[var(--warning-border)] p-3 flex items-start gap-2">
                <AlertTriangle
                  className="w-3.5 h-3.5 mt-0.5 shrink-0 text-[var(--warning)]"
                  aria-hidden
                />
                <p className="text-[11px] text-[var(--muted)] leading-relaxed">
                  Don&apos;t close this tab, refresh, or navigate away until it finishes. Interrupting key
                  generation mid-way leaves setup incomplete and the fees already paid.
                </p>
              </div>

              {error && <ErrorNote {...error} />}
            </>
          )}

          {stage === 'done' && (
            <div className="card p-5 sm:p-6 space-y-5">
              <div className="flex items-center gap-2.5">
                <span className="w-7 h-7 shrink-0 rounded-full grid place-items-center bg-[var(--success-surface)] border border-[var(--success-border)]">
                  <Check className="w-4 h-4 text-[var(--success)]" aria-hidden />
                </span>
                <span className="text-sm font-bold">Keys generated and active</span>
              </div>

              {/* The same list the user just watched, all ticked — a fresh success screen would throw away
                  the context they built up over the last minute. */}
              <CreationChecklist steps={steps} activeStepIndex={steps.length} complete />

              <Button size="lg" onClick={onFinish} className="w-full">
                Open my wallet
                <ArrowRight className="w-4 h-4 shrink-0" aria-hidden />
              </Button>
            </div>
          )}
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
